# Site
title:              HERDEM
bio:                'HERDEM, duygusal yoğunluğu yüksek Alternatif Rock tarzında eserlere hayat veren ve kendi yapım firması HERVOX etiketiyle dinleyicilerle buluşan bağımsız bir Ses Sanatçısıdır.HERDEM’in müzikal altyapısı yalnızca modern alternatif rock’a değil, klasik müzik eğitimine de dayanmaktadır, opera şan eğitimi almış bir müzik öğretmeni olup; bestecilik, vokal performansı, kayıt, düzenleme ve prodüksiyon süreçlerini de aktif olarak bizzat yürütmektedir.Söz yazarı ŞEHBAL YAŞAR ile 10’dan fazla eserde ortak çalışmalar gerçekleştirmiştir. Bu çalışmalarda besteler, kayıt süreçleri ve düzenlemeler HERDEM tarafından yapılmıştır. 
Yayınlanan parçalar arasında öne çıkan eserlerinden bazıları:
•	Bu Şehir (Temmuz 2024)
•	Neden Biz (Mayıs 2026)
Bu iki çalışma, Spotify editörleri tarafından “New Music Friday” listelerine eklenerek dikkat çekici bir başarı elde etmiştir.
HERDEM yalnızca müzik üretimiyle değil; aynı zamanda sinematik görsel dünyası, AI destekli klip konseptleri ve gerçekçi atmosfer tasarımlarıyla da öne çıkar. Özellikle dramatik hikâye anlatımı, yalnız karakterler ve metaforik imgeler projelerinin görsel kimliğinin temelini oluşturur.

description:        "Müzisyen"
locale:             tr_TR
baseurl: "" # the subpath of your site, e.g. /blog
url: ""https://herdemofficial.github.io"" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   "somiibo-themes"

# Social
analytics-id:       "UA-109502418-1"
twitter:            
facebook:           HERDEM
instagram:          Herdem Official
github:             herdemofficial

# personal
location:           İstanbul, TR
phone:              
email:              info@herdemofficial.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
